version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  app:
    build:
      context: ..
      dockerfile: docker-config/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: auth_db
      DB_TYPE: mysql
      DB_PORT: 3306